Document: acdt
Title: Debian acdt Manual
Author: <insert document author here>
Abstract: This manual describes what acdt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/acdt/acdt.sgml.gz

Format: postscript
Files: /usr/share/doc/acdt/acdt.ps.gz

Format: text
Files: /usr/share/doc/acdt/acdt.text.gz

Format: HTML
Index: /usr/share/doc/acdt/html/index.html
Files: /usr/share/doc/acdt/html/*.html
